### PR TITLE
Optionally enable combining without setting the keyboard flags

### PR DESCRIPTION
**Pull request by TyberiusPrime**
My app is using crossterm with stderr instead of stdout,
so enabling the combination would fail with "The keyboard enhancement status could not be read within a normal duration".

This patch adds a function to consider combination enabled without pushing the flags. Then it's up to the caller to have those in place correctly.

Alternatively, I could submit a patch that allows choosing stdout/stderr.

### CODE REVIEW

**Comment by Canop** [comment]
> Alternatively, I could submit a patch that allows choosing stdout/stderr.

Let's consider that later.

For API clarity and to allow later internal changes, I think a function explicitly telling the Combiner that the capacity has been checked and the flags have been pushed would be better, eg `keyboard_enhancement_flags_already_pushed()` (this means storing the flag and changing the `enable_combining` function).

**Comment by TyberiusPrime** [comment]
Sure thing, like this?

I've called the function set_keyboard_enhancement_flags_externally_managed()
since it also affects the popping when/if calling disable_combining.

**Comment by Canop** [comment]
Good thinking

**Comment by Canop** [comment]
Merged, and available in crates.io in version 0.6.4

**Pull request merged**
